package com.eventsphere.backend.entity;

import jakarta.persistence.*;
import lombok.*;

/**
 * Maps to the OAUTH_USERS table in Oracle 26ai Free (FREEPDB1).
 *
 * ID generated by Oracle trigger trg_oauth_user_setup:
 *   'OAU-' || LPAD(seq_oauth_user_identity.NEXTVAL, 4, '0')
 * e.g. OAU-0001, OAU-0002 ...
 *
 * This entity is SEPARATE from User — OAuth2 users (Google/GitHub) are
 * stored here so the existing USERS table is never touched.
 *
 * Fields that OAuth2 does NOT provide are nullable:
 *   oauthPhoneNo — OAuth2 providers don't share phone numbers
 *
 * oauthDummyPw — SHA-256(UUID) stored so the column stays NOT NULL,
 * but the user never actually logs in with a password.
 *
 * JWT token for these users uses oauthUserId as the 'sub' claim
 * and "user" as the role — identical claims format to regular users.
 * This means all existing JWT-protected endpoints work transparently.
 */
@Entity
@Table(name = "OAUTH_USERS")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class OAuthUser {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "OAUTH_USER_ID")
    private String oauthUserId;

    @Column(name = "OAUTH_FIRST_NAME", length = 25, nullable = false)
    private String oauthFirstName;

    @Column(name = "OAUTH_LAST_NAME", length = 25, nullable = false)
    private String oauthLastName;

    /** Provider email — used as unique key to detect returning OAuth2 users. */
    @Column(name = "OAUTH_EMAIL", length = 64, nullable = false, unique = true)
    private String oauthEmail;

    /** Auto-generated from email prefix. Stored so username-based lookups work. */
    @Column(name = "OAUTH_USERNAME", length = 30, nullable = false, unique = true)
    private String oauthUsername;

    /** SHA-256(UUID) dummy — never used for login. NOT NULL in DB. */
    @Column(name = "OAUTH_DUMMY_PW", length = 64, nullable = false)
    private String oauthDummyPw;

    /** Always null for OAuth2 users — providers don't share phone numbers. */
    @Column(name = "OAUTH_PHONENO", length = 10)
    private String oauthPhoneNo;

    /** 'google' | 'github' */
    @Column(name = "OAUTH_PROVIDER", length = 10, nullable = false)
    private String oauthProvider;

    /** Profile picture URL from Google ('picture') or GitHub ('avatar_url'). May be null. */
    @Column(name = "OAUTH_PHOTO_URL", length = 255)
    private String oauthPhotoUrl;
}