package com.eventsphere.backend.entity;

import jakarta.persistence.*;
import lombok.*;

/**
 * Maps to the USERS table in Oracle 26ai Free (FREEPDB1).
 *
 * ID generated by Oracle trigger trg_user_setup:
 *   'U-' || LPAD(seq_user_identity.NEXTVAL, 4, '0')
 * e.g. U-0001, U-0002 ...
 *
 * Password: SHA-256(UTF-8, no salt) → 64-char lowercase hex.
 *
 * EMAIL max length in DB is VARCHAR2(32) — enforce this in RegisterUserRequest too.
 */
@Entity
@Table(name = "USERS")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class User
{
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "USER_ID")
    private String userId;

    @Column(name = "USER_FIRST_NAME", length = 25, nullable = false)
    private String userFirstName;

    @Column(name = "USER_LAST_NAME", length = 25, nullable = false)
    private String userLastName;

    @Column(name = "USER_EMAIL", length = 32, nullable = false, unique = true)
    private String userEmail;

    @Column(name = "USER_PHONENO", length = 10)
    private String userPhoneNo;

    @Column(name = "USER_USERNAME", length = 30, nullable = false, unique = true)
    private String userUsername;

    @Column(name = "USER_PASSWORD", length = 64, nullable = false)
    private String userPassword;
}